object Versions {
    const val CORE_KTX = "1.13.0"
    const val ANNOTATION = "1.1.0"
    const val KOTLIN_VERSION = "1.8.0"
    const val HILT_VERSION = "2.44"
    const val ROOM_VERSION = "2.5.0"
    const val COMPOSE_VERSION = "1.4.0"
    const val PAGING_VERSION = "3.1.1"
    const val PAGING_COMPOSE_VERSION = "1.0.0-alpha14"
    const val GSON_VERSION = "2.8.9"
    const val COMPOSE_ACTIVITY_VERSION = "1.4.0"
    const val COMPOSE_COIL_VERSION = "2.2.0"
    const val NAVIGATION_VERSION = "2.5.3"
    const val HILT_NAVIGATION_VERSION = "1.0.0"
    const val COMPOSE_LIFECYCLE_VERSION = "2.7.0"
    const val RETROFIT_VERSION = "2.9.0"
    const val OKHTTP_VERSION = "4.8.1"
    const val OKHTTP_LOGGING_VERSION = "4.9.3"
    const val CONVERTER_GSON_VERSION = "2.9.0"
    const val COROUTINES_VERSION = "1.7.3"
    const val IMMUTABLE_VERSION = "0.3.7"
    const val SWIPER_VERSION = "0.30.1"
}
